/**
 * Standard HTTP & Core API domain error codes.
 * Codified directly from youten-ai-core-api (internal/constants/error.go & response.go).
 */

export const ApiErrorCode = {
  OK: 'OK',
  ERROR: 'ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  NOT_FOUND: 'NOT_FOUND',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',

  // Core API Domain-specific error codes
  ERR_USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
  ERR_RECORDING_NOT_FOUND: 'ERR_RECORDING_NOT_FOUND',
  CONFLICT_PROCESSING: 'CONFLICT_PROCESSING',
  ERR_ALREADY_COMPLETED: 'ERR_ALREADY_COMPLETED',
  ERR_INVALID_RETRY_STATE: 'ERR_INVALID_RETRY_STATE',
  SUMMARY_VERSION_LIMIT: 'SUMMARY_VERSION_LIMIT',
  ERR_SUMMARY_NOT_FOUND: 'ERR_SUMMARY_NOT_FOUND',
  ERR_EMAIL_ALREADY_EXISTS: 'ERR_EMAIL_ALREADY_EXISTS',
  ERR_SSRF_BLOCKED: 'ERR_SSRF_BLOCKED',
  ERR_INVALID_IMPORT_URL: 'ERR_INVALID_IMPORT_URL',
  ERR_IMPORT_FETCH_FAILED: 'ERR_IMPORT_FETCH_FAILED',
  NO_TRANSCRIPT: 'NO_TRANSCRIPT',
} as const;

export type ApiErrorCode = (typeof ApiErrorCode)[keyof typeof ApiErrorCode];
